include ($$_PRO_FILE_PWD_/WarpDrive/include/external.pri)

HEADERS += \
    $$_PRO_FILE_PWD_/WarpDrive/3DMaths/Billboard.hpp              \
    $$_PRO_FILE_PWD_/WarpDrive/3DMaths/glm.h                      \
    $$_PRO_FILE_PWD_/WarpDrive/3DMaths/GLMesh.hpp                   \
    $$_PRO_FILE_PWD_/WarpDrive/3DMaths/glmint.hpp                   \
    $$_PRO_FILE_PWD_/WarpDrive/3DMaths/Material.hpp                 \
    $$_PRO_FILE_PWD_/WarpDrive/3DMaths/Model.hpp                    \
    $$_PRO_FILE_PWD_/WarpDrive/3DMaths/ModelLoader.hpp              \
    $$_PRO_FILE_PWD_/WarpDrive/3DMaths/Teapot.hpp                   \
    $$_PRO_FILE_PWD_/WarpDrive/3DMaths/Vertex.hpp                   \
    $$_PRO_FILE_PWD_/WarpDrive/3DMaths/Viewport.hpp                 \
    $$_PRO_FILE_PWD_/WarpDrive/BaseMaths/Capsule.hpp                \
    $$_PRO_FILE_PWD_/WarpDrive/BaseMaths/ClipLineSegBox.hpp         \
    $$_PRO_FILE_PWD_/WarpDrive/BaseMaths/Frustrum.hpp               \
    $$_PRO_FILE_PWD_/WarpDrive/BaseMaths/LineSeg.hpp                \
    $$_PRO_FILE_PWD_/WarpDrive/BaseMaths/Matrix44.hpp               \
    $$_PRO_FILE_PWD_/WarpDrive/BaseMaths/Plane.hpp                  \
    $$_PRO_FILE_PWD_/WarpDrive/BaseMaths/Quaternion.hpp             \
    $$_PRO_FILE_PWD_/WarpDrive/BaseMaths/Rect.hpp                   \
    $$_PRO_FILE_PWD_/WarpDrive/BaseMaths/Sphere.hpp                \
    $$_PRO_FILE_PWD_/WarpDrive/BaseMaths/Tri.hpp                    \
    $$_PRO_FILE_PWD_/WarpDrive/BaseMaths/Vec2.hpp                   \
    $$_PRO_FILE_PWD_/WarpDrive/BaseMaths/Vec3.hpp                   \
    $$_PRO_FILE_PWD_/WarpDrive/BaseMaths/Vec4.hpp                   \
    $$_PRO_FILE_PWD_/WarpDrive/BaseSystem/ConfigLoader.hpp          \
    $$_PRO_FILE_PWD_/WarpDrive/BaseSystem/DisplayManager.hpp        \
    $$_PRO_FILE_PWD_/WarpDrive/BaseSystem/Err.hpp                   \
    $$_PRO_FILE_PWD_/WarpDrive/BaseSystem/Factory.hpp               \
    $$_PRO_FILE_PWD_/WarpDrive/BaseSystem/FileManager.hpp           \
    $$_PRO_FILE_PWD_/WarpDrive/BaseSystem/Game.hpp                  \
    $$_PRO_FILE_PWD_/WarpDrive/BaseSystem/GameObject.hpp            \
    $$_PRO_FILE_PWD_/WarpDrive/BaseSystem/GameState.hpp             \
    $$_PRO_FILE_PWD_/WarpDrive/BaseSystem/ManagedFile.hpp           \
    $$_PRO_FILE_PWD_/WarpDrive/BaseSystem/Memory.hpp                \
    $$_PRO_FILE_PWD_/WarpDrive/BaseSystem/OBJLoader.hpp             \
    $$_PRO_FILE_PWD_/WarpDrive/BaseSystem/Score.hpp                 \
    $$_PRO_FILE_PWD_/WarpDrive/BaseSystem/StringProc.hpp            \
    $$_PRO_FILE_PWD_/WarpDrive/BaseSystem/TeapotLoaderState.hpp     \
    $$_PRO_FILE_PWD_/WarpDrive/BaseSystem/TTFManager.hpp            \
    $$_PRO_FILE_PWD_/WarpDrive/BaseSystem/SDLEventHandler.hpp       \
    $$_PRO_FILE_PWD_/WarpDrive/Display/Camera.hpp                   \
    $$_PRO_FILE_PWD_/WarpDrive/Display/Colour.hpp                   \
    $$_PRO_FILE_PWD_/WarpDrive/Display/SDLImage.hpp                 \
    $$_PRO_FILE_PWD_/WarpDrive/Display/RGBAColour.hpp               \
    $$_PRO_FILE_PWD_/WarpDrive/Display/RGBColour.hpp                \
    $$_PRO_FILE_PWD_/WarpDrive/Display/SDLTTF.hpp                   \
    $$_PRO_FILE_PWD_/WarpDrive/Display/Texture.hpp                  \
    $$_PRO_FILE_PWD_/WarpDrive/Events/glColorEvent.hpp              \
    $$_PRO_FILE_PWD_/WarpDrive/Events/ObjectEvent.hpp               \
    $$_PRO_FILE_PWD_/WarpDrive/Events/PanAndTiltEvent.hpp           \
    $$_PRO_FILE_PWD_/WarpDrive/Events/TimedMoveEvent.hpp            \
    $$_PRO_FILE_PWD_/WarpDrive/Events/TimedRemoveEvent.hpp          \
    $$_PRO_FILE_PWD_/WarpDrive/Events/Timeline.hpp                  \
    $$_PRO_FILE_PWD_/WarpDrive/Events/TimelineKey.hpp               \
    $$_PRO_FILE_PWD_/WarpDrive/Events/TKAddEvent.hpp                \
    $$_PRO_FILE_PWD_/WarpDrive/Events/TKDrawTeapot.hpp              \
    $$_PRO_FILE_PWD_/WarpDrive/Events/TKMoveObject.hpp              \
    $$_PRO_FILE_PWD_/WarpDrive/Events/TKPlayMusic.hpp               \
    $$_PRO_FILE_PWD_/WarpDrive/Events/TKUseObject.hpp               \
    $$_PRO_FILE_PWD_/WarpDrive/Physics/AlignedBoundingBox.hpp       \
    $$_PRO_FILE_PWD_/WarpDrive/Physics/CollisionSystem.hpp          \
    $$_PRO_FILE_PWD_/WarpDrive/Physics/Octree.hpp                   \
    $$_PRO_FILE_PWD_/WarpDrive/Physics/VoxelGrid.hpp                \
    $$_PRO_FILE_PWD_/WarpDrive/Sound/SoundFX.hpp                    \
    $$_PRO_FILE_PWD_/WarpDrive/Sound/SoundManager.hpp               \
    $$_PRO_FILE_PWD_/WarpDrive/Display/AnimSheet.hpp                \
    $$_PRO_FILE_PWD_/WarpDrive/BaseSystem/SDLFontManager.hpp        \
    $$_PRO_FILE_PWD_/WarpDrive/Display/Sprite.hpp                   \
    $$_PRO_FILE_PWD_/WarpDrive/Display/TextureSheet.hpp


SOURCES += \
    $$_PRO_FILE_PWD_/WarpDrive/3DMaths/Billboard.cpp              \
    $$_PRO_FILE_PWD_/WarpDrive/3DMaths/GLMesh.cpp                 \
    $$_PRO_FILE_PWD_/WarpDrive/3DMaths/Material.cpp               \
    $$_PRO_FILE_PWD_/WarpDrive/3DMaths/Model.cpp                  \
    $$_PRO_FILE_PWD_/WarpDrive/3DMaths/Vertex.cpp                 \
    $$_PRO_FILE_PWD_/WarpDrive/3DMaths/glm.c                      \
    $$_PRO_FILE_PWD_/WarpDrive/3DMaths/glm_util.c                 \
    $$_PRO_FILE_PWD_/WarpDrive/3DMaths/glmimg.c                   \
    $$_PRO_FILE_PWD_/WarpDrive/3DMaths/glmimg_sdl.c               \
    $$_PRO_FILE_PWD_/WarpDrive/BaseMaths/Capsule.cpp              \
    $$_PRO_FILE_PWD_/WarpDrive/BaseMaths/ClipLineSegBox.cpp       \
    $$_PRO_FILE_PWD_/WarpDrive/BaseMaths/Frustrum.cpp             \
    $$_PRO_FILE_PWD_/WarpDrive/BaseMaths/LineSeg.cpp              \
    $$_PRO_FILE_PWD_/WarpDrive/BaseMaths/Matrix44.cpp             \
    $$_PRO_FILE_PWD_/WarpDrive/BaseMaths/Plane.cpp                \
    $$_PRO_FILE_PWD_/WarpDrive/BaseMaths/Quaternion.cpp           \
    $$_PRO_FILE_PWD_/WarpDrive/BaseMaths/Sphere.cpp               \
    $$_PRO_FILE_PWD_/WarpDrive/BaseSystem/ConfigLoader.cpp        \
    $$_PRO_FILE_PWD_/WarpDrive/BaseSystem/DisplayManager.cpp      \
    $$_PRO_FILE_PWD_/WarpDrive/BaseSystem/Err.cpp                 \
    $$_PRO_FILE_PWD_/WarpDrive/BaseSystem/FileManager.cpp         \
    $$_PRO_FILE_PWD_/WarpDrive/BaseSystem/Game.cpp                \
    $$_PRO_FILE_PWD_/WarpDrive/BaseSystem/GameObject.cpp          \
    $$_PRO_FILE_PWD_/WarpDrive/BaseSystem/ManagedFile.cpp         \
    $$_PRO_FILE_PWD_/WarpDrive/BaseSystem/Memory.cpp              \
    $$_PRO_FILE_PWD_/WarpDrive/BaseSystem/Score.cpp               \
    $$_PRO_FILE_PWD_/WarpDrive/BaseSystem/StringProc.cpp          \
    $$_PRO_FILE_PWD_/WarpDrive/BaseSystem/TeapotLoaderState.cpp   \
    $$_PRO_FILE_PWD_/WarpDrive/BaseSystem/TTFManager.cpp          \
    $$_PRO_FILE_PWD_/WarpDrive/BaseSystem/SDLEventHandler.cpp     \
    $$_PRO_FILE_PWD_/WarpDrive/Display/Camera.cpp                 \
    $$_PRO_FILE_PWD_/WarpDrive/Display/SDLImage.cpp               \
    $$_PRO_FILE_PWD_/WarpDrive/Display/SDLTTF.cpp                 \
    $$_PRO_FILE_PWD_/WarpDrive/Display/Texture.cpp                \
    $$_PRO_FILE_PWD_/WarpDrive/Events/glColorEvent.cpp            \
    $$_PRO_FILE_PWD_/WarpDrive/Events/PanAndTiltEvent.cpp         \
    $$_PRO_FILE_PWD_/WarpDrive/Events/TimedMoveEvent.cpp          \
    $$_PRO_FILE_PWD_/WarpDrive/Events/TimedRemoveEvent.cpp        \
    $$_PRO_FILE_PWD_/WarpDrive/Events/Timeline.cpp                \
    $$_PRO_FILE_PWD_/WarpDrive/Events/TKMoveObject.cpp            \
    $$_PRO_FILE_PWD_/WarpDrive/Events/TKUseObject.cpp             \
    $$_PRO_FILE_PWD_/WarpDrive/Physics/AlignedBoundingBox.cpp     \
    $$_PRO_FILE_PWD_/WarpDrive/Sound/SoundFX.cpp                  \
    $$_PRO_FILE_PWD_/WarpDrive/Sound/SoundManager.cpp             \
    $$_PRO_FILE_PWD_/WarpDrive/Display/AnimSheet.cpp              \
    $$_PRO_FILE_PWD_/WarpDrive/BaseSystem/SDLFontManager.cpp      \
    $$_PRO_FILE_PWD_/WarpDrive/Display/Sprite.cpp                 \
    $$_PRO_FILE_PWD_/WarpDrive/Display/TextureSheet.cpp


